Repository snipsco/snips-nlu, pull requests merged in 2019-01, with the labels that each got.

#737 Add word cooccurrence as intent classification features
  docs/source/api.rst
  snips_nlu/common/utils.py
  snips_nlu/default_configs/config_de.py
  snips_nlu/default_configs/config_en.py
  snips_nlu/default_configs/config_es.py
  snips_nlu/default_configs/config_fr.py
  snips_nlu/default_configs/config_it.py
  snips_nlu/default_configs/config_ja.py
  snips_nlu/default_configs/config_ko.py
  snips_nlu/entity_parser/builtin_entity_parser.py
  snips_nlu/entity_parser/custom_entity_parser.py
  snips_nlu/entity_parser/entity_parser.py
  snips_nlu/exceptions.py
  snips_nlu/intent_classifier/__init__.py
  snips_nlu/intent_classifier/featurizer.py
  snips_nlu/intent_classifier/log_reg_classifier.py
  snips_nlu/intent_parser/deterministic_intent_parser.py
  snips_nlu/nlu_engine/nlu_engine.py
  snips_nlu/pipeline/configs/__init__.py
  snips_nlu/pipeline/configs/config.py
  snips_nlu/pipeline/configs/intent_classifier.py
  snips_nlu/result.py
  snips_nlu/slot_filler/keyword_slot_filler.py
  snips_nlu/string_variations.py
  snips_nlu/tests/doctests.py
  snips_nlu/tests/test_builtin_entity_parser.py
  snips_nlu/tests/test_config.py
  snips_nlu/tests/test_deterministic_intent_parser.py
  snips_nlu/tests/test_intent_classifier_featurizer.py
  snips_nlu/tests/test_log_reg_intent_classifier.py
  snips_nlu/tests/test_utils.py
  snips_nlu/tests/utils.py
Labels: enhancement, model breaking

#740 Return probability of None intent
  docs/source/tutorial.rst
  setup.py
  snips_nlu/intent_classifier/log_reg_classifier.py
  snips_nlu/intent_parser/deterministic_intent_parser.py
  snips_nlu/intent_parser/probabilistic_intent_parser.py
  snips_nlu/nlu_engine/nlu_engine.py
  snips_nlu/result.py
  snips_nlu/tests/test_deterministic_intent_parser.py
  snips_nlu/tests/test_log_reg_intent_classifier.py
  snips_nlu/tests/test_nlu_engine.py
  snips_nlu/tests/test_result.py
  snips_nlu/tests/utils.py
Labels: api-breaking, enhancement

#741 Improve error handling when persisting and loading
  snips_nlu/common/utils.py
  snips_nlu/exceptions.py
  snips_nlu/intent_classifier/featurizer.py
  snips_nlu/intent_classifier/log_reg_classifier.py
  snips_nlu/intent_parser/deterministic_intent_parser.py
  snips_nlu/intent_parser/probabilistic_intent_parser.py
  snips_nlu/nlu_engine/nlu_engine.py
  snips_nlu/pipeline/processing_unit.py
  snips_nlu/slot_filler/crf_slot_filler.py
  snips_nlu/tests/test_nlu_engine.py
Labels: enhancement
